# Generated by Django 5.2.7 on 2026-06-11 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_deleteduser_intalkinguser_callmode'),
    ]

    operations = [
        migrations.AddField(
            model_name='intalkinguser',
            name='token_version',
            field=models.IntegerField(default=0),
        ),
    ]
