# Generated by Django 5.2.7 on 2026-06-15 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_inflcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='intalkinguser',
            name='login_fail_count',
            field=models.IntegerField(default=0),
        ),
    ]
