# Generated by Django 5.2.7 on 2026-06-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_intalkinguser_login_fail_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='intalkinguser',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
