# Generated by Django 5.2.7 on 2026-06-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_intalkinguser_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intalkinguser',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, unique=True),
        ),
    ]
