# Generated by Django 5.2.7 on 2026-07-10 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_intalkinguser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intalkinguser',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
