# Generated by Django 5.2.7 on 2026-07-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_intalkinguser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intalkinguser',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
