# Generated by Django 5.2.7 on 2026-09-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_intalkinguser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='intalkinguser',
            name='push_platform',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='intalkinguser',
            name='push_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
