# Generated by Django 5.2.7 on 2026-03-23 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infllist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infllist',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='infllist',
            name='last',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
