# Generated by Django 5.2.7 on 2026-06-13 11:56

import django.db.models.deletion
import infllist.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infllist', '0002_infllist_duration_infllist_last'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(db_index=True, max_length=160, unique=True)),
                ('fan_track', models.FileField(blank=True, null=True, upload_to=infllist.models.recording_path)),
                ('infl_track', models.FileField(blank=True, null=True, upload_to=infllist.models.recording_path)),
                ('merged', models.FileField(blank=True, null=True, upload_to=infllist.models.recording_path)),
                ('duration', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('infl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
